<?php
use Hyva\Theme\ViewModel\HyvaCsp;

/** @var HyvaCsp $hyvaCsp */
?>

<script>
    const inpostStandardMethodCode = 'inpostlocker_standard';
    const inpostStandardCourierMethodCode = 'inpostcourier_standard';
    // STANDARD
    function inpostModal() {
        return Object.assign(
            hyva.modal(),
            {
                showInpostModal() {
                    this.show('geowidget');
                },
                hideInpostModal() {
                    this.hide('geowidget');
                },
            }
        );
    }
    function inpostGeowidget() {
        return {
            openInpostModal() {
                this.$dispatch('open-geowidget');
            },
        };
    }
    // Courier
    function inpostModalCourier() {
        return Object.assign(
            hyva.modal(),
            {
                showInpostModalCourier() {
                    this.show('geowidget-courier');
                },
                hideInpostModalCourier() {
                    this.hide('geowidget-courier');
                },
            }
        );
    }
    function inpostGeowidgetCourier() {
        return {
            openInpostModalCourier() {
                this.$dispatch('open-geowidget-courier');
            },
        };
    }
    window.addEventListener('alpine:init', () => {
        Alpine.data('inpostModal', inpostModal);
        Alpine.data('inpostModalCourier', inpostModalCourier);
        Alpine.data('inpostGeowidget', inpostGeowidget);
        Alpine.data('inpostGeowidgetCourier', inpostGeowidgetCourier);
    }, {once: true});

</script>
<?php $hyvaCsp->registerInlineScript() ?>
